name: Build and deploy Java project to Azure Function App - InkassoFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: InkassoFunction # Set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # Set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # Set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Java Sdk
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Restore Project Dependencies Using Mvn
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1F55295BF1F4B83ACE8DFDF5620EFEBF }}
          package: '${{ env.PACKAGE_DIRECTORY }}'
